### ISSUE TITLE
will systemd 245 be backported as well?

### ISSUE THREAD

**Issue by jdef** [facebookincubator/rpm-backports#13]

**Comment by davide125** [comment]
Yes, we generally aim to track the latest stable for this backport. We'll begin testing 245 soon, and update the backport accordingly. cc @anitazha

**Comment by davide125** [comment]
Updated to 245 in https://github.com/facebookincubator/rpm-backports/commit/1ac92ddc09436342227886aafb2def65dc4dbebb
