### ISSUE TITLE
is there a way to only install the missing systemd-timesyncd ?

### ISSUE THREAD

**Issue by openalmeida** [facebookincubator/rpm-backports#8]
Hi,

the current version Centos 7 shipped is fine for me,
but systemd-timesyncd (it connects to dhcp client systemd-networkd via dbus)
is missing  (cut off ? no idea why redhat did this),
thus i can not fetch NTP settings via systemd-networkd from DHCP server's OPTION 42.

i suppose to only install missing part may makes me less pain than entire systemd update.

**Comment by davide125** [comment]
I wouldn't recommend mixing different parts of systemd from different versions; while timesyncd is reasonably self contained, you're still likely to run into issues. What you can do however is grab the src.rpm for the systemd version shipped in CentOS 7, and rebuild it with timesyncd enabled.

**Comment by openalmeida** [comment]
awesome, i do will rebuild systemd as you said.
