### ISSUE TITLE
Can you gents not simply set up a yum repo?

### ISSUE THREAD

**Issue by lejeczek** [facebookincubator/rpm-backports#9]
Why can you gents not simply set up a yum repo? With all the power and resources you can get it should be easy peasy, no?

**Comment by davide125** [comment]
There's a community copr with an older version of the systemd backport, see https://maciej.lasyk.info/2016/Dec/16/systemd-231-latest-in-centos-7-thx-to-facebook/ for details. You're welcome to create and maintain one as well if you'd like. At the moment we do not plan to setup a public Yum repo for these backports.
